### ISSUE TITLE
Connection with pivot?

### ISSUE THREAD

**Issue by stoffern** [nodkz/graphql-compose#14]
Hi,
This is a merge of MongoDB and GraphQL compose question. but i will try

How would you solve this?
Can it be solved with only 2 tables?. i want to make shure that there are different types of employees in the company
```js
//User Table
{
  id: userId,
  firstName: 'Frank',
  lastName: 'Sinatra',
  email: 'frank@sinatra.com'
}

//Company table
{
  id: companyId,
  name: 'Wallmart',
  description: 'awsome'
}

//Employeeconnection
{
  user: userId,
  company: companyId,
  employeeStatus: 'Cleaner'
}
```

**Comment by nodkz** [comment]
Defenetly it should be merged according to mongodb denormalization.

First of all you should decide which collection will store relation:
- user (if you will have much more queries, than to company)
- company (otherwise)
- or both of them (if number of queries is same, or you need higher query speed).

To be sure that company has different employee types, you should create `unique` index.

The best feature of mongodb that it expand arrays in index.
Eg. `{ a: [ 1, 2, 3 ] }` you may query like `a: 2`. Internally mongodb will store 3 records in index for example doc. So `a` field may contain single value or array, for querying it works similarly.

If we go deeper, mongodb can store array of objects (id and empStatus). But I don't remember some restrictions, need to read MongoDB docs. It too difficult to do via mobile.
